### ISSUE TITLE
Send query and variables in json body

### ISSUE THREAD

**Issue by flexzuu** [machinebox/graphql#12]
I think the issues #7 and #11 are both related to the the client sending data and variables as FormDataContentType but most server implementations expect them as application json in body like

```
{
  "query":  `query here`,
  "variables": obj with variables here
}
```

**Comment by kelvinji2009** [comment]
@flexzuu I have tried to use other content-type, but still not working.

**Comment by matryer** [comment]
OK so this is definitely worth changing then?

**Comment by flexzuu** [comment]
yeah i think we should be agnostic how the server accepts it and add default implementations for the most common ones.

**Comment by kamushadenes** [comment]
Having problems on interacting with graphql-go/graphql because of this.

**Comment by matryer** [comment]
What happens if you're submitting files? The body has to be a multipart, and can't be JSON?

**Comment by phated** [comment]
@matryer APIs like Graphcool have a separate API endpoint for submitting files (with multipart) - https://www.graph.cool/docs/reference/graphql-api/file-management-eer4wiang0

**Comment by kamushadenes** [comment]
Quick hack on https://github.com/kamushadenes/graphql got me going by implementing RunJSON()

**Comment by matryer** [comment]
Pull master, there’s an official way to do that now too.

**Comment by matryer** [comment]
@flexzuu this is fixed - please confirm?

**Comment by matryer** [comment]
Closing assuming this is fixed.
