### ISSUE TITLE
Is object input type supported for requests?

### ISSUE THREAD

**Issue by suman-anand-grab** [machinebox/graphql#16]
Is the object input type supported for making requests.
https://medium.com/graphql-mastery/json-as-an-argument-for-graphql-mutations-and-queries-3cd06d252a04

**Comment by matryer** [comment]
I don't see why not. From what I understand, they just go into the query. Is that right?

**Comment by suman-anand-grab** [comment]
So I just create a struct and send it as a variable?

**Comment by matryer** [comment]
I assume you’d just make a query that had the input stuff at the top? So it goes into the actual query string. Then use variables to fill in the values when you use the type.

This is more of a GraphQL question I think, and I’m far from being an expert.

**Comment by suman-anand-grab** [comment]
Great. Thanks i will close this issue.
