### ISSUE TITLE
ResponseStruct?

### ISSUE THREAD

**Issue by cedricve** [machinebox/graphql#26]
What is this ResponseStruct?

**Comment by pwmcintyre** [comment]
I was a little confused too, a little more doco would be useful

@cedricve I found the tests show how to use it

https://github.com/machinebox/graphql/blob/master/graphql_json_test.go#L37

Basically a map of strings, the string being a json, so you could then unmarshal it into your actual struct
Eg. https://stackoverflow.com/questions/47270595/golang-parse-json-string-to-struct

I'll be playing with this in the week, will loop back if I get something working

**Comment by cedricve** [comment]
hey @pwmcintyre, yes Indeed I used the map of stings and that works properly. Thanks for getting in touch ;)
